php-version: "8.4"
spc-version: "2.8.2"

extensions:
  common:
    - bcmath
    - bz2
    - ctype
    - curl
    - dom
    - fileinfo
    - filter
    - gd
    - iconv
    - mbstring
    - mbregex
    - opcache
    - openssl
    - phar
    - session
    - simplexml
    - sockets
    - sodium
    - tokenizer
    - xml
    - zip
    - zlib
  non_windows:
    - intl

libraries:
  - zlib
  - bzip2
  - openssl
  - libssh2
  - libiconv-win
  - libxml2
  - nghttp2
  - curl
  - libpng
  - libavif
  - libwebp
  - libjpeg
  - freetype
  - onig
  - libsodium
  - xz
  - libzip

sapi:
  - cli

package:
  include-cacert: true
  cacert-path: "cacert.pem"