php-version: "8.4"
spc-version: "2.8.2"

extensions:
  common:
    - bcmath
    - bz2
    - ctype
    - curl
    - dom
    - fileinfo
    - filter
    - gd
    - iconv
    - intl
    - mbstring
    - mbregex
    - opcache
    - openssl
    - phar
    - session
    - simplexml
    - sockets
    - sodium
    - tokenizer
    - xml
    - zip
    - zlib

libraries:
  - freetype
  - libwebp
  - libjpeg

sapi:
  - cli

package:
  include-cacert: true
  cacert-path: "cacert.pem"